config/routes.rb
Rails.application.routes.draw do
  get 'user_preferences/edit'

  put 'user_preferences/update'

  get 'home/index'

  get 'home/show'

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  root to: 'pages#home'

  resources :restaurants, only: [:index, :show] do
    resources :match_lists, only: [ :create, :destroy]
  end

  resources :match_lists do
    resources :evaluations, only: [:create, :index]
  end

  resources :evaluations, only: [:index]

  resources :evaluations, only: [:create] do
    member do
      post :accept
      post :decline
    end
    resources :reservations, only: [:show, :create, :new] do
    end
  end
  resources :users, only: [:index, :edit, :create] do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :match_list
  has_many :users
  belongs_to :restaurant
  belongs_to :selector, foreign_key: :selector_id, class_name: "User"
  belongs_to :selectee, foreign_key: :selectee_id, class_name: "User"
  has_one :reservation
# not sure
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController

  def index
   @received_evaluations = policy_scope(Evaluation).where(selectee_id: current_user.id).where(accepted: nil)
    @sent_evaluations = policy_scope(Evaluation).where(selector_id: current_user.id).where(accepted: nil)

  end

  def accept

    @evaluation = Evaluation.find(params[:id])
    authorize @evaluation
    @evaluation.accepted = true
    if @evaluation.save
       redirect_to new_evaluation_reservation_path(@evaluation)
    end

  end

  def decline
    @evaluation = Evaluation.find(params[:id])
    authorize @evaluation
    @evaluation.accepted = false
    if @evaluation.save
      redirect_to match_list_evaluations_path(@evaluation.match_list_id)
    end
  end

  def create

    @match_list = MatchList.find(params[:match_list_id])
    @restaurant = @match_list.restaurant
    @evaluation = Evaluation.new(selector: current_user, selectee_id: params[:selectee_id], match_list: @match_list, restaurant: @restaurant)
    authorize @evaluation
    @evaluation.save

    redirect_to match_list_evaluations_path(@match_list)
  end



  private

  def eval_params
    params.require(:evaluation).permit(:selector_id,:selectee_id)
  end

  def destroy
    @evaluation = Evaluation.find(params[:Id])
    authorize @evaluation
    @evaluation.destroy
  end


end

app/views/evaluations/index.html.erb
<% if @received_evaluations.any? %>
<div class="container text-center">
  <h1>Invitations you've received</h1>

  <div class="row">
    <% @received_evaluations.each do |evaluation| %>

    <div class="col-xs-12 col-sm-4">
      <div class="card">
        <div class="card-body special-card-body">
          <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= Restaurant.all.first.photo %>')">
            <div class="counter">


              <h3 class="text-white"><%= evaluation.restaurant.name %></h3>

            </div>
          </div>
          <ul class="list-inline card-likes">
            <li>
              <%= cl_image_tag evaluation.selector.photo, :width=>50, :height=>50, gravity: 'face', class: "avatar-large", alt: "user" %>
            </li>
            <li>
              <h6><%= evaluation.selector.username%></h6>
            </li>
          </ul>
          <div class="text-center">
            <div class="row">
              <div class="col-xs-6">
                <%= link_to "Accept", accept_evaluation_path(evaluation), method: :post, class: 'btn btn-primary btn-block' %>

              </div>
              <div class="col-xs-6">
                <%= link_to "Decline", decline_evaluation_path(evaluation), method: :post, class: 'btn btn-danger btn-block' %>

              </div>
            </div>
          </div>
        </div>
        <!--   <a class="card-link" href="#" ></a> -->
      </div>
    </div>
    <% end %>
  </div>
</div>
<% end %>

<% if @sent_evaluations.empty? && @received_evaluations.empty? %>
<div class="no-invitations">
  <div class="no-invitations-message text-center">
    <p>Hey buddie, you have no pending invitations.</p>
  </div>
</div>
<% end %>

<% if @sent_evaluations.any? %>
    <div class="container text-center">
      <h1>Invitations you've sent</h1>
    <div class="row">
        <% @sent_evaluations.each do |evaluation| %>

        <div class="col-xs-12 col-sm-4">
          <div class="card">
            <div class="card-body special-card-body">
              <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= Restaurant.all.first.photo %>')">
                <div class="counter">


                  <h3 class="text-white"><%= evaluation.restaurant.name %></h3>

                </div>
              </div>
              <ul class="list-inline card-likes">
                <li>
                  <%= cl_image_tag evaluation.selectee.photo, :width=>50, :height=>50, gravity: 'face', class: "avatar-large", alt: "user" %>
                </li>
                <li>
                  <h6><%= evaluation.selectee.username%></h6>
                </li>
              </ul>

            </div>
            <!--   <a class="card-link" href="#" ></a> -->
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<% if @sent_evaluations.empty? && @received_evaluations.empty? %>
  <div class="space-footer-no-content"></div>
<% else  %>
  <div class="div-spacer"></div>
<% end %>