config/routes.rb
Rails.application.routes.draw do
  get 'user_preferences/edit'

  put 'user_preferences/update'

  get 'home/index'

  get 'home/show'

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  root to: 'pages#home'

  resources :restaurants, only: [:index, :show] do
    resources :match_lists, only: [ :create, :destroy]
  end

  resources :match_lists do
    resources :evaluations, only: [:create, :index]
  end

  resources :evaluations, only: [:index]

  resources :evaluations, only: [:create] do
    member do
      post :accept
      post :decline
    end
    resources :reservations, only: [:show, :create, :new] do
    end
  end
  resources :users, only: [:index, :edit, :create] do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/views/shared/_flash_messages.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible <%= yield(:alert_class) %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h2 class="white-text">Food Buddies</h2>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5>Meet the rockstars who build this application</h5>
                <ul class="list-inline">
                  <li><%= image_tag("lucas.png", class: "avatar-large") %></li>
                  <li><%= image_tag("george.png", class: "avatar-large") %></li>
                  <li><%= image_tag("ric.png", class: "avatar-large") %></li>
                  <li><%= image_tag("mary.png", class: "avatar-large") %></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 Le Wagon Batch 71 "aka the most awesome batch ever"
            <a class="grey-text text-lighten-4 right" href="#!"></a>
            </div>
          </div>
        </footer>

app/views/shared/_footer2.html.erb
<div id="footer" class="<%= "hidden" if @fix_nav %>">
  <div class="row">
    <div class="col-sm-4">
      <div class="copyright text-left">
        <span>© 2017 Offtime</span>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="social-media">
        <div class="row text-center">
          <div class="col-sm-3">
           <%= link_to "", "", class: "fa fa-youtube"%>
         </div>
         <div class="col-sm-3">
          <%= link_to "", "", class: "fa fa-instagram"%>
        </div>
        <div class="col-sm-3">
          <%= link_to "", "",class: "fa fa-facebook"%>
        </div>
        <div class="col-sm-3">
          <%= link_to "", "", class: "fa fa-twitter"%>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
  <div class="row">
  <div class="col-sm-offset-3">
  <div class="menu">
      <div class="col-sm-3">
        <%= link_to "Policies", 'pages#home' %>
      </div>
      <div class="col-sm-3">
        <%= link_to "Sitemap", 'pages#home' %>
      </div>
      <div class="col-sm-3">
        <%= link_to "Support", 'pages#home' %>
      </div>
      </div>
    </div>
  </div>
  </div>
</div>
</div>

app/views/shared/_login_form.html.erb
<div class="form-inputs">
  <%= f.input :email, required: false, autofocus: true %>
  <%= f.input :password, required: false %>
  <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
</div>
<div class="form-actions">
</div>
<%= render "devise/shared/links" %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:special_navbar_class) %>">
  <!-- Logo -->
  <ul class="list-inline navbar-wagon-brand">
    <li>
      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </li>
    <li>
      <h1  class="hidden-xs hidden-sm">Food Buddies</h1>
    </li>
  </ul>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to evaluations_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue"><%= Evaluation.where(selectee_id: current_user.id).where(accepted: nil).length %></div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag avatar_url(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_preferences_edit_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login text link -->
      <%# link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= modal_toggle 'Login', dialog: '#login', class: 'navbar-wagon-item navbar-wagon-link' %>
      <%= modal_toggle 'Sign-up', dialog: '#signup', class: 'navbar-wagon-item navbar-wagon-link btn btn-success' %>
    <% end %>

    <!-- Button (call-to-action) -->

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to user_preferences_edit_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %></li>
      </ul>
    </div>
  </div>
</div>

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <%= modal_dialog :id => "login",
           :header => { :show_close => true, :title => content_tag(:h2, 'Login') },
           :body   => content_tag(:div, (render "shared/login_form", f: f)),
           :footer => (f.button :submit, "Log in") %>
<% end %>

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <%= modal_dialog :id => "signup",
           :header => { :show_close => true, :title => content_tag(:h2, 'Sign-up') },
           :body   => content_tag(:div, (render "shared/signup_form", f: f)),
           :footer => (f.button :submit, "Sign-up") %>
<% end %>

app/views/shared/_restaurant_map_box.html.erb
<%= link_to restaurant.name, restaurant_path(restaurant) %>
<%# link_to restaurant.photo, restaurant_path(restaurant) %>

app/views/shared/_search_form.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
    <form action="/restaurants" method="get" class="form-inline" name="Go!">


          <div class="input-group">
          <input type="text" class="form-control margin-xs" id="user-location" name="user_location" value="<%= @user_location %>" placeholder="Address" autocomplete="off" required >
          <div class="input-group-addon pointer">
                  <span onclick="getLocation();" class="glyphicon glyphicon-map-marker"></span>
              </div>
          </div>

          <div class="input-group date form_datetime" id='datepicker'>
              <input type="text" class="form-control" value="<%= @date %>" name="date" placeholder="27/03/12" autocomplete="off" required>
              <div class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </div>
          </div>
          <div class="input-group date form_datetime" id="timepicker">
          <input type="text" class="form-control margin-xs" name="start_time"  value="<%= @start_time %>" placeholder="20:30" autocomplete="off" required>
          <div class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
              </div>
          </div>

          <input  type="hidden" name='user_location_address' id='user-location-address' value="<%= @user_location_address %>"/>

          <select name="food_type" class="form-control">
            <option type="text" value="">Food Type</option>
            <% Restaurant::FOOD_TYPES.each do |foodtype| %>
              <option type="text" value="<%=foodtype%>" <% if @food_type == foodtype %>selected="selected"<% end %>><%=foodtype.capitalize%></option>
            <% end %>
          </select>
          <br>
          <input id="ex23" type="text" name="range" />
          <!-- <input type="range" name="geolocation" id="points" value="50" min="18" max="120" data-popup-enabled="true">
 -->
          <br>
          <input  type="submit" value="Go!" class="btn btn-primary">
    </form>
  </div>
</div>
</div>
<%= content_for(:after_js) do %>
              <script type="text/javascript">
                  $(function () {
                        $('#datepicker').datetimepicker({
                          format: 'DD/MM/YYYY',
                          viewMode: 'years'
                          });
                        $('#timepicker').datetimepicker({
                          format: 'LT',

                          });
                      });

                  $("#ex23").slider({
                    ticks: [1, 3, 5],
                    ticks_labels: ['1 km', '3km', 'City'],
                    value: 3,
                    ticks_tooltip: true,
                    step: 0.1,
                    tooltip_position:'bottom'
                      // ticks_positions: ["1", "3", "6"],
                      // ticks_snap_bounds: 1,
                    // formatter: function(value) {
                    //   return 'Current value: ' + value;
                    // },
                  });
                  var x = document.getElementById("user-location");

                  function getLocation() {
                      if (navigator.geolocation) {
                          navigator.geolocation.getCurrentPosition(showPosition, showError);
                      } else {
                          x.innerHTML = "Geolocation is not supported by this browser.";
                      }
                  }

                  function showPosition(position) {
                      document.getElementById("user-location").value = "My Location";

                      var lat = position.coords.latitude;
                      var lng = position.coords.longitude;

                      $.ajax({
                            type: "GET",
                            url: "https://maps.googleapis.com/maps/api/geocode/json?latlng=" + lat + "," + lng,
                            success: function(data) {
                              // get the lat and lng from the json data
                            // var message = jqXHR.responseText.error_message;
                            // console.log("DATA; ", data);
                            // console.log("DATA results; ", data.results);
                            // console.log("DATA results example; ", data.results[0]);
                            // console.log("DATA results example addr; ", data.results[0].formatted_address);

                            var addr = data.results[0].formatted_address
                            document.getElementById("user-location-address").value = addr;
                            // $("#addr").text(addr);

                            if (data.results.length == 0) {

                              showError("no array");

                            } else {
                              $("#error-message").html("").parent().removeClass("has-error");

                            }
                            },
                            error: function(jqXHR) {
                              console.error(jqXHR.responseText);

                              showError(jqXHR.responseJSON.error_message);
                            }
                          });
                      }
                  function showError(error) {
                      switch(error.code) {
                          case error.PERMISSION_DENIED:
                              x.innerHTML = "User denied the request for Geolocation."
                              break;
                          case error.POSITION_UNAVAILABLE:
                              x.innerHTML = "Location information is unavailable."
                              break;
                          case error.TIMEOUT:
                              x.innerHTML = "The request to get user location timed out."
                              break;
                          case error.UNKNOWN_ERROR:
                              x.innerHTML = "An unknown error occurred."
                              break;
                          default:
                            console.log(error)

                      }
                  }
                  // getLocation();

                      </script>
              <% end %>


<!-- <input class='hidden' name='datehide' id='datehide' value='before'/> -->

app/views/shared/_search_form.html.erb
    <div class="col-md-12 text-center search-form">
    <form action="/restaurants" method="get" class="form-inline" name="Go!">


          <div class="input-group serach-labels">
          <input type="text" class="form-control margin-xs" id="user-location" name="user_location" value="<%= @user_location %>" placeholder="Address" autocomplete="off" required >
          <div class="input-group-addon pointer">
                  <span onclick="getLocation();" class="glyphicon glyphicon-map-marker"></span>
              </div>
          </div>

          <div class="input-group date form_datetime serach-labels" id='datepicker'>
              <input type="text" class="form-control" value="<%= @date %>" name="date" placeholder="27/03/12" autocomplete="off" required>
              <div class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </div>
          </div>
          <div class="input-group date form_datetime serach-labels" id="timepicker">
          <input type="text" class="form-control margin-xs" name="start_time"  value="<%= @start_time %>" placeholder="20:30" autocomplete="off" required>
          <div class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
              </div>
          </div>

          <!-- This line is passing params with geolocations -->
          <input  type="hidden" name='user_location_address' id='user-location-address' value="<%= @user_location_address %>"/>

          <!-- <select name="start_time" class="form-control" id="time-picker" onmousedown="if(this.options.length>5){this.size=5;}" onchange="this.blur()"  onblur="this.size=0;" >
            <option type="text" value="">Pick Time</option>
            <% Restaurant::HOURS.each do |hour| %>
              <option type="text" value="<%=hour%>" <% if @start_time == hour %>selected="selected"<% end %>><%=hour%></option>
            <% end %>
          </select> -->
          <select name="food_type" class="form-control serach-labels">
            <option type="text" value="">Food Type</option>
            <% Restaurant::FOOD_TYPES.each do |foodtype| %>
              <option type="text" value="<%=foodtype%>" <% if @food_type == foodtype %>selected="selected"<% end %>><%=foodtype.capitalize%></option>
            <% end %>
          </select>
          <br>
          <br>
          <input  type="submit" value="Find place!" class="btn btn-go">
    </form>
  </div>

<%= content_for(:after_js) do %>
              <script type="text/javascript">
                  $(function () {
                        $('#datepicker').datetimepicker({
                          format: 'DD/MM/YYYY',
                          });
                        $('#timepicker').datetimepicker({
                          format: 'LT',

                          });
                      });

                  $( function() {
                    var handle = $( "#ex23" );
                    $( "#slider" ).slider({
                      create: function() {
                                        handle.text( $( this ).slider( "value" ) );
                      },
                      slide: function( event, ui ) {
                        handle.text( ui.value );
                      }
                    });
                  } );
                  var x = document.getElementById("user-location");

                  function getLocation() {
                      if (navigator.geolocation) {
                          navigator.geolocation.getCurrentPosition(showPosition, showError);
                      } else {
                          x.innerHTML = "Geolocation is not supported by this browser.";
                      }
                  }

                  function showPosition(position) {
                      document.getElementById("user-location").value = "My Location";

                      var lat = position.coords.latitude;
                      var lng = position.coords.longitude;

                      $.ajax({
                            type: "GET",
                            url: "https://maps.googleapis.com/maps/api/geocode/json?latlng=" + lat + "," + lng,
                            success: function(data) {
                              // get the lat and lng from the json data
                            // var message = jqXHR.responseText.error_message;
                            // console.log("DATA; ", data);
                            // console.log("DATA results; ", data.results);
                            // console.log("DATA results example; ", data.results[0]);
                            // console.log("DATA results example addr; ", data.results[0].formatted_address);

                            var addr = data.results[0].formatted_address
                            document.getElementById("user-location-address").value = addr;
                            // $("#addr").text(addr);

                            if (data.results.length == 0) {

                              showError("no array");

                            } else {
                              $("#error-message").html("").parent().removeClass("has-error");

                            }
                            },
                            error: function(jqXHR) {
                              console.error(jqXHR.responseText);

                              showError(jqXHR.responseJSON.error_message);
                            }
                          });
                      }
                  function showError(error) {
                      switch(error.code) {
                          case error.PERMISSION_DENIED:
                              x.innerHTML = "User denied the request for Geolocation."
                              break;
                          case error.POSITION_UNAVAILABLE:
                              x.innerHTML = "Location information is unavailable."
                              break;
                          case error.TIMEOUT:
                              x.innerHTML = "The request to get user location timed out."
                              break;
                          case error.UNKNOWN_ERROR:
                              x.innerHTML = "An unknown error occurred."
                              break;
                          default:
                            console.log(error)

                      }
                  }
                  // getLocation();
                  $( function() {
                  $( "#number" )
                    .selectmenu()
                    .selectmenu( "menuWidget" )
                    .addClass( "overflow" );
                    });
                      </script>


              <% end %>
<%= content_for(:js_file) do %>
<%= javascript_include_tag 'google_maps_autocomplete' %>
<% end %>

<!-- <input class='hidden' name='datehide' id='datehide' value='before'/> -->

app/views/shared/_search_form_2.html.erb
    <div class="col-md-12 text-center search-form">
    <form action="/restaurants" method="get" class="form-inline" name="Go!">


          <div class="input-group search-labels">
          <input type="text" class="form-control margin-xs" id="user-location" name="user_location" value="<%= params[:user_location] %>" placeholder="Address" autocomplete="off" required >
          <div class="input-group-addon pointer">
                  <span onclick="getLocation();" class="glyphicon glyphicon-map-marker"></span>
              </div>
          </div>

          <div class="input-group date form_datetime search-labels" id='datepicker'>
              <input type="text" class="form-control" value="<%= @date %>" name="date" placeholder="27/03/12" autocomplete="off" required>
              <div class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </div>
          </div>
          <div class="input-group date form_datetime search-labels" id="timepicker">
          <input type="text" class="form-control margin-xs" name="start_time"  value="<%= @start_time %>" placeholder="20:30" autocomplete="off" required>
          <div class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
              </div>
          </div>
          <!-- This line is passing params with geolocations -->
          <input  type="hidden" name='user_location_address' id='user-location-address' value="<%= @user_location_address %>"/>


          <select name="food_type" class="input-group form-control search-labels">
            <option type="text" value="">Food Type</option>
            <% Restaurant::FOOD_TYPES.each do |foodtype| %>
              <option type="text" value="<%=foodtype%>" <% if @food_type == foodtype %>selected="selected"<% end %>><%=foodtype.capitalize%></option>
            <% end %>
          </select>

          <!-- <br>
          <div class="search-labels-2">
            <label for="hash-input">Hash Your Preferences</label>
            <input data-role="tagsinput" class="input-group margin-xs input" id="hash-input" type="text" name="hash_tag_pref" placeholder="#classicalmusic, #mozart"/>
          </div> -->
          <br>
          <div class="search-labels-2">
            <label for="hash-input">Range from your location</label>
          <div id="slider"></div>
            <p>
              <input type="hidden" class="ui-slider-handle" type="text" id="range-value" name="range" value="<%= @range %>">

              <label id="range_lable"></label>

            </p>
            <!-- <input class="ui-slider-handle" id="ex23" type="text" name="range" value="<%= @range %>" /> -->

          <!-- <input type="range" name="geolocation" id="points" value="50" min="18" max="120" data-popup-enabled="true">

 -->
          </div>
          <br>
          <input id="button-find-your-buddy" type="submit" value="Find your Buddy!" class="btn btn-go">
    </form>
  </div>

<%= content_for(:after_js) do %>
              <script type="text/javascript">
                  $(document).ready(function () {
                        $('#datepicker').datetimepicker({
                          format: 'DD/MM/YYYY',
                          });
                        $('#timepicker').datetimepicker({
                          format: 'LT',
                         });
                      });
                  $(function () {
                    $('#hash-input').val()
                  });
                  $( function() {
                    var handle = $( "#range_lable" );
                      default_value = <%= @range %>;
                      current_val_element = $("#range_lable");
                      current_val_element.text(default_value);

                      $( "#slider" ).slider({
                        value: default_value,
                        min: 0,
                        max: 15,
                        step: 0.1,

                        slide: function( event, ui ) {
                          value = ui.value;
                          current_val_element.text(value);
                          $('#range-value').val(value)
                        }
                      });
                      });

                  var x = document.getElementById("user-location");

                  function getLocation() {
                      if (navigator.geolocation) {
                          navigator.geolocation.getCurrentPosition(showPosition, showError);
                      } else {
                          x.innerHTML = "Geolocation is not supported by this browser.";
                      }
                  }
                  function showPosition(position) {
                      document.getElementById("user-location").value = "My Location";

                      var lat = position.coords.latitude;
                      var lng = position.coords.longitude;

                      $.ajax({
                            type: "GET",
                            url: "https://maps.googleapis.com/maps/api/geocode/json?latlng=" + lat + "," + lng,
                            success: function(data) {
                            var addr = data.results[0].formatted_address
                            document.getElementById("user-location-address").value = addr;
                            // $("#addr").text(addr);

                            if (data.results.length == 0) {

                              showError("no array");

                            } else {
                              $("#error-message").html("").parent().removeClass("has-error");

                            }
                            },
                            error: function(jqXHR) {
                              console.error(jqXHR.responseText);

                              showError(jqXHR.responseJSON.error_message);
                            }
                          });
                      }
                  function showError(error) {
                      switch(error.code) {
                          case error.PERMISSION_DENIED:
                              x.innerHTML = "User denied the request for Geolocation."
                              break;
                          case error.POSITION_UNAVAILABLE:
                              x.innerHTML = "Location information is unavailable."
                              break;
                          case error.TIMEOUT:
                              x.innerHTML = "The request to get user location timed out."
                              break;
                          case error.UNKNOWN_ERROR:
                              x.innerHTML = "An unknown error occurred."
                              break;
                          default:
                            console.log(error)

                      }
                  }
                  // getLocation();

                      </script>
              <% end %>
<%= content_for(:js_file) do %>
<%= javascript_include_tag 'google_maps_autocomplete' %>
<% end %>

<!-- <input class='hidden' name='datehide' id='datehide' value='before'/> -->

app/views/shared/_signup_form.html.erb
  <%= f.error_notification %>
      <%= f.input :email, required: true, autofocus: true %>
      <%= f.input :username, required: true %>
      <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
      <%= f.input :password_confirmation, required: true %>


<%= render "devise/shared/links" %>