config/routes.rb
Rails.application.routes.draw do
  get 'user_preferences/edit'

  put 'user_preferences/update'

  get 'home/index'

  get 'home/show'

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  root to: 'pages#home'

  resources :restaurants, only: [:index, :show] do
    resources :match_lists, only: [ :create, :destroy]
  end

  resources :match_lists do
    resources :evaluations, only: [:create, :index]
  end

  resources :evaluations, only: [:index]

  resources :evaluations, only: [:create] do
    member do
      post :accept
      post :decline
    end
    resources :reservations, only: [:show, :create, :new] do
    end
  end
  resources :users, only: [:index, :edit, :create] do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_after_action :verify_policy_scoped, only: [:index, :show]
  def index
    session[:conversations] ||= []


    # @users = User.online_now.where.not(id: current_user)
    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end

  def show

    #@user_sender = User.sender_id
   # @user_recip = User.recipient_id
   #session[:conversations] ||= []

    #@user = User.find_by(:user_id, @u
    # @users = User.online_now.where.not(id: current_user)
    #@users = User.all.where.not(id: current_user, )
    #@conversations = Conversation.includes(:recipient, :messages)
                                # .find(session[:conversations])
  end


end

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>

            <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    (function() {
      $(document).on('click', '.toggle-window', function(e) {
        e.preventDefault();
        var panel = $(this).parent().parent();
        var messages_list = panel.find('.messages-list');

        panel.find('.panel-body').toggle();
        panel.attr('class', 'panel panel-default');

        if (panel.find('.panel-body').is(':visible')) {
          var height = messages_list[0].scrollHeight;
          messages_list.scrollTop(height);
        }
      });
    })();
  </script>
<% end %>

app/views/home/show.html.erb
<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
            <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    (function() {
      $(document).on('click', '.toggle-window', function(e) {
        e.preventDefault();
        var panel = $(this).parent().parent();
        var messages_list = panel.find('.messages-list');

        panel.find('.panel-body').toggle();
        panel.attr('class', 'panel panel-default');

        if (panel.find('.panel-body').is(':visible')) {
          var height = messages_list[0].scrollHeight;
          messages_list.scrollTop(height);
        }
      });
    })();
  </script>
<% end %>