config/routes.rb
Rails.application.routes.draw do
  get 'user_preferences/edit'

  put 'user_preferences/update'

  get 'home/index'

  get 'home/show'

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  root to: 'pages#home'

  resources :restaurants, only: [:index, :show] do
    resources :match_lists, only: [ :create, :destroy]
  end

  resources :match_lists do
    resources :evaluations, only: [:create, :index]
  end

  resources :evaluations, only: [:index]

  resources :evaluations, only: [:create] do
    member do
      post :accept
      post :decline
    end
    resources :reservations, only: [:show, :create, :new] do
    end
  end
  resources :users, only: [:index, :edit, :create] do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  FOOD_TYPES = ["mexican", "italian", "japanese", "american", "french", "portuguese"]
  HOURS = ["00:00", "00:15", "00:30", "00:45", "1:00", "1:15", "1:30", "1:45", "2:00", "2:15", "2:30", "2:45", "3:00", "3:15", "3:30", "3:45", "4:00", "4:15", "4:30", "4:45", "5:00", "5:15", "5:30", "5:45", "6:00", "6:15", "6:30", "6:45", "7:00", "7:15", "7:30", "7:45", "8:00", "8:15", "8:30", "8:45", "9:00", "9:15", "9:30", "9:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30", "21:45", "22:00", "22:15", "22:30", "22:45", "23:00", "23:15", "23:30", "23:45"]

  has_many :match_lists, dependent: :destroy
  has_many :evaluations
  has_many :reservations
  has_many :users, through: :match_lists
  validates :name, presence: true
  validates :address, presence: true
  validates :food_type, inclusion: { in: FOOD_TYPES, allow_nil: false }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  skip_before_action :authenticate_user!, only: :index

  def index
       # @restaurants = Restaurant.find_by_food_type(params[:food_type])
       # @food_type = params[:food_type "mexican"]


    @food_type = params[:food_type]
    @date = params[:date]
    @start_time = params[:start_time]

    @range = params[:range]

    @user_location_address = params[:user_location_address]

    @user_location = params[:user_location]

    @user_location_requested = get_address

    # user_hash_pref = current_user.hash_pref.chopfjdklsj

    if @range == nil
      @restaurants = policy_scope(Restaurant).where(food_type: @food_type)
      @range = 7.5
    else
      @restaurants = policy_scope(Restaurant).near(@user_location_requested, @range.to_i).where(food_type: @food_type)
    end

    # if user_hash_pref.any?


    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow render_to_string(partial: "/shared/restaurant_map_box", locals: { restaurant: restaurant })
      # marker.picture({
      #       url: render_to_string(partial: "/shared/restaurant_map_box", locals: { restaurant: restaurant }),
      #       width: 32,
      #       height: 32,
      #   })
    end

        # @restaurants = Restaurant.where(food_type: @food_type)
  end


  def show
    @restaurant = Restaurant.find(params[:id])
    @alert_message = "You are viewing #{@restaurant.name}"
    @range = params[:range]

    @hash_tag_pref = session[:hash_tag_pref]
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @match_list = MatchList.new()
    @evaluation = Evaluation.new()
    @date = params[:date]
    @start_time = params[:start_time]
    @hash_tag_pref = current_user.hash_tag_pref
    #@user_in_list = @restaurant.match_lists.any? {|i| i.user == current_user}
    @user_match_list = MatchList.where(user_id: current_user.id, restaurant_id: @restaurant.id)
   # @count = MatchList.all.where(restaurant_id: Restaurant[params[:id]]).length
  end



  def get_address
    if @user_location == "My Location"
      @user_location_address
    else
      @user_location
    end
  end


  # def user_location_range
  #   @range = params[:range]
  #   @user_location_requested = get_address
  #   # loc = @user_location.split(",").map {|a| a.to_f } # [38.732656999999996, -9.1421262]
  #   @restaurants = Restaurant.near(@user_location_requested, @range.to_i).where(food_type: @food_type)
  # end

end

app/views/restaurants/_restaurant.html.erb
  <div class="col-xs-12 col-sm-4">

    <div class="card">
      <%= link_to "", restaurant_path(restaurant, date: @date, start_time: @start_time), class: 'card-link' %>
      <div class="card-body">
        <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= restaurant.photo %>')">
        <div class="counter">
          </div>

        </div>
        <div class="card-likes row">
        <div class="col-xs-9">
          <h6><%= restaurant.name %></h6>
        </div>
        <div class="col-xs-3">

          <h6><i class="fa fa-smile-o"></i><%= restaurant.match_lists.count %></h6>
        </div>
        </div>
      </div>

    <!--   <a class="card-link" href="#" ></a> -->

  </div>
</div>

app/views/restaurants/_user.html.erb
<li>
  <div class="user-card">
    <div class="avatar-card">
      <div class="user-avatar padded-right">
        <%= cl_image_tag match_list.user.photo, :width=>50, :height=>50, gravity: 'face', class: "avatar-large", alt: "user" %>
      </div>

      <div class="user-and-date">
        <p class="user-name text-left">
          <%= match_list.user.username  %>
        </p>
        <p class="date-info text-left">
          <%= match_list.date.strftime("%d %b, %Y") %> <%= match_list.start_time.strftime("%H:%M") %>
        </p>
      </div>
    </div>


    <% if  !user_match_list.nil? && user_match_list.any? %>

      <div class="invite-button">

          <div class="invite center-inline  ">
            <%= form_tag match_list_evaluations_path(match_list) do %>
              <%= hidden_field_tag 'selectee_id', match_list.user.id %>
              <%= submit_tag 'invite', class: 'fake-btn' %>
            <% end %>
          </div>

      </div>
    <% end %>

  </div>
</li>

<hr>

app/views/restaurants/create.js.erb
//$('.choose-btn').on('click', function(event) {
 // event.preventDefault();

////$(".choose-btn").hide();

//$//


//});

//$('.btn-danger').on('click', function(event) {
  //event.preventDefault();

//$(".choose-btn").show();

//$


//

app/views/restaurants/index.html.erb
<div class="container">
    <%= render 'shared/search_form_2' %>
</div>
<div class="container">
  <div class="row">
    <div class="cards-container">
    <%= render @restaurants %>
    <!-- <div class="badge-container">
          <%#MatchList.all.where(restaurant_id: params[:id]).each do |i| %>

          <%# puts i.count %>
          <i class="fa fa-envelope-o"></i>

          <%# end %>
          <div class="badge badge-blue"> </div>
        </div> -->
    <!-- build the html for listing cards and titles -->
  </div>
  </div>
</div>
<div class="container">
  <div id="map-label-container">
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div id="map"></div>
          </div>
            <div class="col-xs-12 col-md-6">
            <h3>Food Type: <strong><%= @food_type %></strong></h3>
              <p>Your Location: <strong><%= @user_location_requested %></strong></p>
            </div>
    </div>
  </div>
</div>

 <% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(5);
        }
      });
    });
  <% end %>
<% end %>

app/views/restaurants/show.html.erb
<% content_for :meta_title, "#{@restaurant.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @restaurant.description %>
<% content_for :meta_image, @restaurant.photo %>




<div class="restaurant-card text-center">
  <p><%= @restaurant.food_type.titleize %></p>

  <h2> <%= @restaurant.name %></h2>
  <%=  @restaurant.address %>
        <div class="restaurant center">
          <% if policy(MatchList).create? %>
          <%= render 'match_lists/form', restaurant: @restaurant, match_list: @match_list %>
          <% end  %>
        </div>

    <div class="match center">
      <ul id="user-list">
        <% @restaurant.match_lists.each do |match_list| %>
          <% if Time.now.to_date == match_list.date %>
            <% unless match_list.user == current_user %>
              <%= render "restaurants/user", match_list: match_list, user_match_list: @user_match_list %>
            <% end %>
          <% end %>

          <div class="div-spacer"></div>

          <div class="remove center center-inline hidden">
            <% if policy(match_list).destroy?%>
              <%= link_to "X", restaurant_match_list_path(match_list.restaurant,match_list), method: :delete, data: {confirm: "Are you sure?" }, class: 'btn btn-danger' %>
            <% end %>
          </div>
        <% end %>

      </ul>
    </div>
</div>

<div class="div-spacer"></div>

<div class="row text-center">
    <%= link_to "Back", restaurants_path, class: 'btn btn-default btn-back' %>
</div>

<div class="div-spacer"></div>